### ISSUE TITLE
Question: How to include multiple file types in config pattern

### ISSUE THREAD

**Issue by georgewrmarshall** [elderfo/react-native-storybook-loader#110]
Just wondering how one would include multiple file types in the config pattern using a glob?

I've tried ` "\"**/*.stories.{ts|tsx|js|jsx|mdx}\""` and `"**/*.stories.(ts|tsx|js|jsx|mdx)"`

```
"config": {
    "react-native-storybook-loader": {
      "searchDir": [
        "./app/components"
      ],
      "pattern": "\"**/*.stories.{ts|tsx|js|jsx|mdx}\"",
      "outputFile": "./storybook/storyLoader.js"
    }
}
```

**Comment by joustava** [comment]
Think it night work like this? `../stories/**/*.stories.@(js|jsx|ts|tsx)`

**Comment by georgewrmarshall** [comment]
Sorry for the late reply! Just getting back to working on this and your suggestion works like a charm thanks @joustava 🙏
