### ISSUE TITLE
rnstl did not work

### ISSUE THREAD

**Issue by Yasser-Belatreche** [elderfo/react-native-storybook-loader#113]
I got those weird line when i run  `npm run prestorybook` or `npx rnstl`.
![Screenshot from 2022-01-11 16-19-08](https://user-images.githubusercontent.com/79541979/148970051-b27f2580-7073-45f5-93f7-7a3b0c9e50e7.png)

Here is my `package.json` file

![Screenshot from 2022-01-11 16-21-31](https://user-images.githubusercontent.com/79541979/148970503-1b76c611-4373-4ac0-be87-24ac73d0278c.png)
![Screenshot from 2022-01-11 16-21-40](https://user-images.githubusercontent.com/79541979/148970517-b087f722-a05b-4e89-a88d-4e465e5ea086.png)

OS: ubuntu 20.04

**Comment by elderfo** [comment]
Fixed in 2.0.5

Ref: https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/
