### ISSUE TITLE
(suggestion) make the loader search multiple directories

### ISSUE THREAD

**Issue by xareelee** [elderfo/react-native-storybook-loader#14]
I'm starting to migrate my code to monorepo with multiple packages using [lerna](lernajs.io). Now I have two directories for snapshots: `./src` and `./packages`. I need `react-native-storybook-loader` to search multiple directories to support this monorepo.

From this (in `package.json`):

```json
{
  "config": {
    "react-native-storybook-loader": {
      "searchDir": "./src",
    }
  }
}
```

to this:

```json
{
  "config": {
    "react-native-storybook-loader": {
      "searchDir": ["./src", "./packages"],
    }
  }
}
```

Would you help improve this?

**Comment by xareelee** [comment]
Or use a new prop `matches` to set up the loader for different use cases if necessary.

```json
{
  "config": {
    "react-native-storybook-loader": {
      "matches":  [
        {
          "searchDir": "./src",
          "pattern": "**/*.stories.js",
          "outputFile": "./storybook/storyLoaderForSrc.js"
        },
        {
          "searchDir": "./packages",
          "pattern": "**/ui/*.stories.js",
          "outputFile": "./storybook/storyLoaderForPackages.js"
        }
      ]
    }
  }
}
```

**Comment by xareelee** [comment]
Or make the cli tool scriptable:

```shell
node ./node_modules/.bin/rnstl --searchDir "./src" --pattern "**/*.stories.js" --outputFile "./storybook/storyLoader.js"
```

and then use `npm`/`yarn` `scripts` to setup multiple loaders.

**Comment by elderfo** [comment]
Thanks @xareelee, I really like all three ideas. I think it makes sense to start with adding support for arrays as a setting for `searchDir`.  I can probably get that done over my lunch out and push it out for you. 

After that, I think I may move on to the cli options and lastly `matches`. I will create new issues for those.

**Comment by xareelee** [comment]
@elderfo Great! Very appreciated!

BTW, I think **storybook** and **storyshots** should include your library to load `.stories` automatically for development and testing.
