### ISSUE TITLE
Updating install docs

### ISSUE THREAD

**Issue by tmaly1980** [elderfo/react-native-storybook-loader#30]
Integrating with the existing storybook app really only requires changing two lines in storybook.js generated from getstorybook. The example you have is obsolete, code is under @storybook/getstorybook now. All it takes is changing the configure() line:

import { loadStories } from './storyLoader'; // import stories
configure(loadStories, module);

**Comment by elderfo** [comment]
Feel free to submit a PR with the updated documentation 🙂
