### ISSUE TITLE
Revert to npm mock-fs once node 7.7.1 fix is applied

### ISSUE THREAD

**Issue by elderfo** [elderfo/react-native-storybook-loader#5]
Temporarily using https://github.com/not-an-aardvark/mock-fs/tree/update-binding-stat-lstat-fstat

Related to https://github.com/tschaub/mock-fs/issues/197

**Comment by tschaub** [comment]
Fix from @not-an-aardvark published as `mock-fs@4.2`.

**Comment by elderfo** [comment]
Thank you @tschaub!
