### ISSUE TITLE
Rename file doest not update correctly

### ISSUE THREAD

**Issue by hushicai** [elderfo/react-native-storybook-loader#50]
As shown below, I renamed `captcha.js` to `pages/login/captcha.js`, but `storyLoader` not updated as expected.

![image](https://user-images.githubusercontent.com/1249423/32933579-ffb9175a-cb2f-11e7-8b94-db4c9e9885f2.png)

**Comment by elderfo** [comment]
How are you renaming the file?

**Comment by hushicai** [comment]
I mean move `captcha.js`to other directory，and story loader will re-gernarate storyLoader.js，but in my case，it just update the loadStories function, without syncing the stories object.
