### ISSUE TITLE
Omit file extension in the generated file

### ISSUE THREAD

**Issue by no23reason** [elderfo/react-native-storybook-loader#51]
Hi, thank you for the great tool.
I have only one problem with it. Could the generated file omit file extensions in the `require` calls? The problem is, that I write the files with `tsx` extension and it gets copied in the `require`s and breaks the whole thing. If I manually erase the file extensions it works properly.

### Current output
```js

// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../components/common/icons/StatusIcon/index.stories.tsx');

}

const stories = [
  '../components/common/icons/StatusIcon/index.stories.tsx',

];

module.exports = {
  loadStories,
  stories,
};
```

### Expected output
```js

// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../components/common/icons/StatusIcon/index.stories');

}

const stories = [
  '../components/common/icons/StatusIcon/index.stories',

];

module.exports = {
  loadStories,
  stories,
};
```

As the `.js` in the `require` call is optional anyway, this change should not break anything.

**Comment by elderfo** [comment]
I fixed the CI for this and published an update: https://github.com/elderfo/react-native-storybook-loader/releases/tag/v1.7.0

**Comment by no23reason** [comment]
Thank you very much :)
