### ISSUE TITLE
How to add stories while running

### ISSUE THREAD

**Issue by EskelCz** [elderfo/react-native-storybook-loader#62]
Hello, thanks for the library. It works great with stories already created. However, sometimes you want to add new story file while the packager is running.
Right now I have to restart storybook to see the new stories. Is there a way to make this dynamic as well?
Thank you.

**Comment by elderfo** [comment]
Few years late on this. I tested with storybook version 5.3.19 and if you run `yarn prestorybook` or `npm prestorybook` to regenerate the storyLoader while storybook is running, it will recognize the new files. I am not sure when this changed

I am going to close this now. When I get a chance, I will look in to a `--watch` flag for rnstl.

**Comment by jenskuhrjorgensen** [comment]
@elderfo That would be an awesome feature! 😄 
Btw, I think you made a small typo, it's `npm run prestorybook`, right?

**Comment by zigcccc** [comment]
Hey @elderfo, any updates re `--watch` flag and/or how this could be done automatically?
