### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by jdoroy** [elderfo/react-native-storybook-loader#84]
First of all, thank you for this awesome project. I just want to know if I can use this with typescript? I've tried doing so but I haven't yet succeeded.

I've followed the instructions here: https://storybook.js.org/docs/configurations/typescript-config/. Tried using both `babel-loader` and `awesome-typescript-loader` but no luck.

Here's the screenshot of what I'm experiencing:

<img width="452" alt="Screen Shot 2019-09-25 at 4 27 50 PM" src="https://user-images.githubusercontent.com/52098608/65583410-ba574e00-dfb1-11e9-98a6-4464039e6b80.png">

**Comment by odjhey** [comment]
do you mean 'detect stories written in typescript?'
If so, yes, it works fine, im using it with typescript. I just changed the pattern to `"pattern": "**/*.story.tsx"` in my `package.json`

I suggest to try and make your Storybook (in typescript) work first before installing RNSTL.

**Comment by jdoroy** [comment]
@odjhey Yup, I've already resolve the issue by doing so. Thank you, anyway 🙏 

Turned out that the error is caused by `react-native` caching issue.
