### ISSUE TITLE
Installation fails when used in lerana monorepo with hoisted dependencies

### ISSUE THREAD

**Issue by amalfra** [elderfo/react-native-storybook-loader#94]
I am trying to use this in a learna monorepo with packages hoisted in root node_modules. It fails saying ```<node_modules path>/out/rnst-cli.js``` not found. I doubt whether it has got something to do with relative paths in bin: https://github.com/elderfo/react-native-storybook-loader/blob/main/package.json#L9

**Comment by amalfra** [comment]
Actually, looking at how jest cli does it: https://github.com/facebook/jest/tree/master/packages/jest-cli

They have ./bin/jest.js in the repo https://github.com/facebook/jest/blob/master/packages/jest-cli/package.json#L31. But here out folder is missing

**Comment by elderfo** [comment]
Thanks for the report. I'll dig in

**Comment by elderfo** [comment]
I published version 2.0.1 which I was able to use in a monorepo which uses lerna and yarn workspaces. Here's my test repo: https://github.com/rnstl/rnstl-lerna-workspace-example

Please let me know if this takes care of your issue, if not, would it be possible to get a sample project which mimics yours?

**Comment by amalfra** [comment]
Fantastic, now it's fixed!!!

**Comment by elderfo** [comment]
Great news
