### ISSUE TITLE
Line ending error using macOS and yarn

### ISSUE THREAD

**Issue by isilher** [elderfo/react-native-storybook-loader#95]
Thanks for this handy tool!

When upgrading to v2.0.1 I encountered the following error running `rnstl`:

> env: node\r: No such file or directory

With some research I found this error results from a line ending issue that often pops up when a release is made from a Windows machine and the machine adding the packages is a macOS machine (how is this still an issue in 2020 :P). 

Apparently, npm consumers won't have the issue since npm changes the line endings programmatically while yarn does not.

See also: https://github.com/yarnpkg/yarn/issues/5480

**Comment by dcolthorp** [comment]
Same here.

**Comment by elderfo** [comment]
I am going to rebuild from my mac to get you guys going.

**Comment by elderfo** [comment]
Fixed in v2.0.2. I used the typescript compiler option to set new lines to lf so it shouldn't matter which machine I build it from 🤞. I'll test from my windows box in a few days.
